# Generated by Django 4.1.2 on 2022-11-30 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_teacher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stuteacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Student_Teacher', to='app.teacher'),
        ),
    ]
