# Generated by Django 4.1.2 on 2022-11-30 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_student_stuteacher'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='student',
            name='stuteacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Student_Teacher', to='app.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('studentclass', 'user', 'School', 'stuteacher')},
        ),
    ]
