# Generated by Django 4.1.2 on 2022-11-30 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_student_school_alter_student_studentclass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='School',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='School_Student', to='app.school'),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentclass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Student_class', to='app.class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='stuteacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Student_Teacher', to='app.teacher'),
        ),
    ]
